# Author: Melinda de Jonge
# Date: 20-09-2022
# Department of Environmental Science, Radboud University Nijmegen
# e-mail: melinda.dejonge@ru.nl

## -------------------------------------------------------------------------------------------------
#'
##--------------------------------------------------------------------------------------------------

FEMB = list(c(~1),
           c(~Diet),
           c(~Habitat),
           c(~logBM),
           c(~InfraType),
           c(~logD),
           c(~logD + Diet),
           c(~logD + Habitat),
           c(~logD + logBM),
           c(~logD + InfraType),
           c(~logD*Diet),
           c(~logD*Habitat),
           c(~logD*logBM),
           c(~logD + Diet + logBM),
           c(~logD + Diet + Habitat),
           c(~logD + Diet + InfraType),
           c(~logD + logBM + Habitat),
           c(~logD + logBM + InfraType),
           c(~logD + Habitat + InfraType),
           c(~logD*Diet + logBM),
           c(~logD*Diet + Habitat),
           c(~logD*Diet + InfraType),
           c(~logD*Diet + logD*logBM),
           c(~logD*Diet + logD*Habitat),
           c(~logD*logBM + Habitat),
           c(~logD*logBM + InfraType),
           c(~logD*logBM + Diet),
           c(~logD*logBM + logD*Habitat),
           c(~logD*Habitat + Diet),
           c(~logD*Habitat + InfraType),
           c(~logD*Habitat + logBM),
           c(~logD + Diet + logBM + Habitat),
           c(~logD + Diet + logBM + InfraType),
           c(~logD + Diet + Habitat + InfraType),
           c(~logD + logBM + Habitat + InfraType),
           c(~logD*Diet + logBM + Habitat),
           c(~logD*Diet + logBM + InfraType),
           c(~logD*Diet + Habitat + InfraType),
           c(~logD*Diet + logD*logBM + Habitat),
           c(~logD*Diet + logD*logBM + InfraType),
           c(~logD*Diet + logD*Habitat + InfraType),
           c(~logD*Diet + logD*Habitat + logBM),
           c(~logD*Diet + logD*Habitat + logD*logBM),
           c(~logD*logBM + Diet + Habitat),
           c(~logD*logBM + Diet + InfraType),
           c(~logD*logBM + Habitat + InfraType),
           c(~logD*logBM + logD*Habitat + InfraType),
           c(~logD*logBM + logD*Habitat + Diet),
           c(~logD*Habitat + logBM + Diet),
           c(~logD*Habitat + logBM + InfraType),
           c(~logD*Habitat + Diet + InfraType),
           c(~logD + Diet + logBM + Habitat + InfraType),
           c(~logD*Diet + logBM + Habitat + InfraType),
           c(~logD*Diet + logD*logBM + Habitat + InfraType),
           c(~logD*Diet + logBM + logD*Habitat + InfraType),
           c(~logD*logBM + Diet + Habitat + InfraType),
           c(~logD*logBM + Diet + logD*Habitat + InfraType),
           c(~logD*Habitat + Diet + logBM + InfraType),
           c(~logD*Diet + logD*logBM + logD*Habitat + InfraType),
           c(~logD + logD2),
           c(~logD + logD2 + Diet),
           c(~logD + logD2 + Habitat),
           c(~logD + logD2 + logBM),
           c(~logD + logD2 + InfraType),
           c(~logD*Diet + logD2),
           c(~logD*Habitat + logD2),
           c(~logD*logBM + logD2),
           c(~logD*Diet + logD2*Diet),
           c(~logD*Habitat + logD2*Habitat),
           c(~logD*logBM + logD2*logBM),
           c(~logD + logD2 + Diet + logBM),
           c(~logD + logD2 + Diet + Habitat),
           c(~logD + logD2 + Diet + InfraType),
           c(~logD + logD2 + logBM + Habitat),
           c(~logD + logD2 + logBM + InfraType),
           c(~logD + logD2 + Habitat + InfraType),
           c(~logD*Diet + logD2 + logBM),
           c(~logD*Diet + logD2 + Habitat),
           c(~logD*Diet + logD2 + InfraType),
           c(~logD*Diet + logD2 + logD*logBM),
           c(~logD*Diet + logD2 + logD*Habitat),
           c(~logD*Diet + logD2*Diet + logBM),
           c(~logD*Diet + logD2*Diet + Habitat),
           c(~logD*Diet + logD2*Diet + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD2*logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD2*Habitat),
           c(~logD*Diet + logD*logBM + logD2*logBM),
           c(~logD*Diet + logD*Habitat + logD2*Habitat),
           c(~logD*logBM + logD2 + Habitat),
           c(~logD*logBM + logD2 + InfraType),
           c(~logD*logBM + logD2 + Diet),
           c(~logD*logBM + logD2 + logD*Habitat),
           c(~logD*logBM + logD2*logBM + Habitat),
           c(~logD*logBM + logD2*logBM + InfraType),
           c(~logD*logBM + logD2*logBM + Diet),
           c(~logD*logBM + logD2*logBM + logD*Habitat),
           c(~logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat),
           c(~logD*logBM + logD*Habitat + logD2*Habitat),
           c(~logD*Habitat + logD2 + Diet),
           c(~logD*Habitat + logD2 + InfraType),
           c(~logD*Habitat + logD2 + logBM),
           c(~logD*Habitat + logD2*Habitat + Diet),
           c(~logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Habitat + logD2*Habitat + logBM),
           c(~logD + logD2 + Diet + logBM + Habitat),
           c(~logD + logD2 + Diet + logBM + InfraType),
           c(~logD + logD2 + Diet + Habitat + InfraType),
           c(~logD + logD2 + logBM + Habitat + InfraType),
           c(~logD*Diet + logD2 + logBM + Habitat),
           c(~logD*Diet + logD2 + logBM + InfraType),
           c(~logD*Diet + logD2 + Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logBM + Habitat),
           c(~logD*Diet + logD2*Diet + logBM + InfraType),
           c(~logD*Diet + logD2*Diet + Habitat + InfraType),
           c(~logD*Diet + logD2 + logD*logBM + Habitat),
           c(~logD*Diet + logD2 + logD*logBM + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + Habitat),
           c(~logD*Diet + logD2*Diet + logD*logBM + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD2*logBM + Habitat),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD2*logBM + InfraType),
           c(~logD*Diet + logD*logBM + logD2*logBM + Habitat),
           c(~logD*Diet + logD*logBM + logD2*logBM + InfraType),
           c(~logD*Diet + logD2 + logD*Habitat + InfraType),
           c(~logD*Diet + logD2 + logD*Habitat + logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD2*Habitat + logBM),
           c(~logD*Diet + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD*Habitat + logD2*Habitat + logBM),
           c(~logD*Diet + logD*Habitat + logD*logBM + logD2),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD*logBM),
           c(~logD*Diet + logD*Habitat + logD2*Habitat + logD*logBM),
           c(~logD*Diet + logD*Habitat + logD*logBM + logD2*logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD2*Habitat + logD*logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD*logBM + logD2*logBM),
           c(~logD*Diet + logD*Habitat + logD2*Habitat + logD*logBM + logD2*logBM),
           c(~logD*Diet + logD2*Diet + logD*Habitat + logD2*Habitat + logD*logBM + logD2*logBM),
           c(~logD*logBM + logD2 + Diet + Habitat),
           c(~logD*logBM + logD2 + Diet + InfraType),
           c(~logD*logBM + logD2 + Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + Diet + Habitat),
           c(~logD*logBM + logD2*logBM + Diet + InfraType),
           c(~logD*logBM + logD2*logBM + Habitat + InfraType),
           c(~logD*logBM + logD2 + logD*Habitat + InfraType),
           c(~logD*logBM + logD2 + logD*Habitat + Diet),
           c(~logD*logBM + logD2*logBM + logD*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + logD*Habitat + Diet),
           c(~logD*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*logBM + logD*Habitat + logD2*Habitat + Diet),
           c(~logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat + Diet),
           c(~logD*Habitat + logD2 + logBM + Diet),
           c(~logD*Habitat + logD2 + logBM + InfraType),
           c(~logD*Habitat + logD2 + Diet + InfraType),
           c(~logD*Habitat + logD2*Habitat + logBM + Diet),
           c(~logD*Habitat + logD2*Habitat + logBM + InfraType),
           c(~logD*Habitat + logD2*Habitat + Diet + InfraType),
           c(~logD + logD2 + Diet + logBM + Habitat + InfraType),
           c(~logD*Diet + logD2 + logBM + Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logBM + Habitat + InfraType),
           c(~logD*Diet + logD2 + logD*logBM + Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + Habitat + InfraType),
           c(~logD*Diet + logD*logBM + logD2*logBM + Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD2*logBM + Habitat + InfraType),
           c(~logD*Diet + logD2 + logBM + logD*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logBM + logD*Habitat + InfraType),
           c(~logD*Diet + logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*logBM + logD2 + Diet + Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + Diet + Habitat + InfraType),
           c(~logD*logBM + logD2 + Diet + logD*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + Diet + logD*Habitat + InfraType),
           c(~logD*logBM + Diet + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + Diet + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Habitat + logD2 + Diet + logBM + InfraType),
           c(~logD*Habitat + logD2*Habitat + Diet + logBM + InfraType),
           c(~logD*Diet + logD*logBM + logD*Habitat + InfraType + logD2),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD*Habitat + InfraType),
           c(~logD*Diet + logD*logBM + logD2*logBM + logD*Habitat + InfraType),
           c(~logD*Diet + logD*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet +  logD*logBM + logD2*logBM + logD*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Diet + logD2*Diet + logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat + InfraType)
)

FERep = list(c(~1),
           c(~Habitat),
           c(~logBM),
           c(~InfraType),
           c(~logD),
           c(~logD + Habitat),
           c(~logD + logBM),
           c(~logD + InfraType),
           c(~logD*Habitat),
           c(~logD*logBM),
           c(~logD + logBM + Habitat),
           c(~logD + logBM + InfraType),
           c(~logD + Habitat + InfraType),
           c(~logD*logBM + Habitat),
           c(~logD*logBM + InfraType),
           c(~logD*logBM + logD*Habitat),
           c(~logD*Habitat + InfraType),
           c(~logD*Habitat + logBM),
           c(~logD + logBM + Habitat + InfraType),
           c(~logD*logBM + Habitat + InfraType),
           c(~logD*logBM + logD*Habitat + InfraType),
           c(~logD*Habitat + logBM + InfraType),
           c(~logD + logD2),
           c(~logD + logD2 + Habitat),
           c(~logD + logD2 + logBM),
           c(~logD + logD2 + InfraType),
           c(~logD*Habitat + logD2),
           c(~logD*logBM + logD2),
           c(~logD*Habitat + logD2*Habitat),
           c(~logD*logBM + logD2*logBM),
           c(~logD + logD2 + logBM + Habitat),
           c(~logD + logD2 + logBM + InfraType),
           c(~logD + logD2 + Habitat + InfraType),
           c(~logD*logBM + logD2 + Habitat),
           c(~logD*logBM + logD2 + InfraType),
           c(~logD*logBM + logD2 + logD*Habitat),
           c(~logD*logBM + logD2*logBM + Habitat),
           c(~logD*logBM + logD2*logBM + InfraType),
           c(~logD*logBM + logD2*logBM + logD*Habitat),
           c(~logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat),
           c(~logD*logBM + logD*Habitat + logD2*Habitat),
           c(~logD*Habitat + logD2 + InfraType),
           c(~logD*Habitat + logD2 + logBM),
           c(~logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Habitat + logD2*Habitat + logBM),
           c(~logD + logD2 + logBM + Habitat + InfraType),
           c(~logD*logBM + logD2 + Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + Habitat + InfraType),
           c(~logD*logBM + logD2 + logD*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + logD*Habitat + InfraType),
           c(~logD*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*logBM + logD2*logBM + logD*Habitat + logD2*Habitat + InfraType),
           c(~logD*Habitat + logD2 + logBM + InfraType),
           c(~logD*Habitat + logD2*Habitat + logBM + InfraType)
)

FEAmph = list(c(~1),
           c(~logBM),
           c(~InfraType),
           c(~logD),
           c(~logD + logBM),
           c(~logD + InfraType),
           c(~logD*logBM),
           c(~logD + logBM + InfraType),
           c(~logD*logBM + InfraType),
           c(~logD + logD2),
           c(~logD + logD2 + logBM),
           c(~logD + logD2 + InfraType),
           c(~logD*logBM + logD2),
           c(~logD*logBM + logD2*logBM),
           c(~logD + logD2 + logBM + InfraType),
           c(~logD*logBM + logD2 + InfraType),
           c(~logD*logBM + logD2*logBM + InfraType)
)
